// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v5/reference-guide/models/enrich-your-models
module.exports = (databaseName) => (sequelize, DataTypes) => {
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v5/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Companies = sequelize.define(`${databaseName}Companies`, {
    name: {
      type: DataTypes.STRING,
    },
  }, {
    tableName: 'companies',
    timestamps: false,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v5/reference-guide/relationships#adding-relationships.
  Companies.associate = (models) => {
    Companies.hasMany(models[`${databaseName}Users`], {
      as: 'users',
      foreignKey: {
        name: 'companyId',
        field: 'company_id',
      },
    });
  };

  return Companies;
};
